correction exo 2

diff --git a/.github/workflows/exo-2.yml b/.github/workflows/exo-2.yml
--- a/.github/workflows/exo-2.yml
+++ b/.github/workflows/exo-2.yml
@@ -1,11 +1,10 @@
-name: Exercice 2
-
+name: build
 on:
   push:
 
 
 jobs:
-  test:
+  build:
     runs-on: windows-latest
     steps:
     - uses: actions/checkout@v7
@@ -15,18 +14,22 @@ jobs:
       with:
         node-version: 24.18.0
 
+    - run: npm
+    - run: npm run build
 
-
-    - uses: actions/cache@v5
-      with:
-        path: ~/.npm
-        key: npm-${{ runner.os}}-${{ hashFiles('package-lock.json') }}
-
-    - run: npm ci
-
-    - run: npm test
+    - run: |
+        if [ ! -d dist]; then
+         echo ""::error:: Le dossier dist/ n'existe pas"
+         exit 1
+        fi
+    
+    - run: npm run test
 
     - uses: actions/upload-artifact@v7
       with:
-      name: build
-      path: dist/
+        name: build
+        path: dist/
+
+    - run: |
+       echo "## Build" >> "$GITHUB_STEP_SUMMARY"
+
